version: '3.7'

services:
  simple-api-1:
    build:
      context: ./simple-api
      dockerfile: Dockerfile
    ports: [ 3001:3001 ]
    environment:
      PORT: 3001
      TEST_FLAG: NORMAL

  simple-api-2:
    build:
      context: ./simple-api
      dockerfile: Dockerfile
    ports: [ 3002:3002 ]
    environment:
      PORT: 3002
      TEST_FLAG: NORMAL

  simple-api-3:
    build:
      context: ./simple-api
      dockerfile: Dockerfile
    ports: [ 3003:3003 ]
    environment:
      PORT: 3003
      TEST_FLAG: ERROR
      TEST_PERIOD: 20

  routing-api:
    build:
      context: ./routing-api
      dockerfile: Dockerfile
    ports: [ 3000:3000 ]
    environment:
      PORT: 3000
      URLS: "http://simple-api-1:3001,http://simple-api-2:3002,http://simple-api-3:3003"
      ROLLING_COUNT_TIMEOUT: 10000
      ROLLING_COUNT_BUCKET: 10
      ERROR_THRESHOLD_PERCENTAGE: 20
      LATENCY_THRESHOLD_PERCENTAGE: 20
      LATENCY_THRESHOLD: 3000
      HEALTHCHECK_PERIOD: 5000
